version: '3'
services:
  database:
    image: mysql:5.6.34
    environment: 
    - MYSQL_ROOT_PASSWORD=pocockn
    - MYSQL_DATABASE=docker_pocockn
    - MYSQL_USER=pocockn
    - MYSQL_PASSWORD=pocockn
    expose:
            - 3306
    ports:
            - 3306:3306
  data-migrator:
    image: pococknick91/database-migrator:0.5.0